### ISSUE TITLE
Reminders not working (alarms 1.3)

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey-issues-dp#29] opened 2017-05-02 08:47 UTC
**What is your Homey version (Settings → System)?**
1.3RC3
**What did you try to achieve?**

Use the senteces on the website from Athom to send a reminder by the FB messenger:

Geheugensteuntjes
Zet een timer voor over twee en een halve minuut
Zet een timer om over 12 minuten de pizza uit de over te halen
https://www.athom.com/nl/ondersteuning/KB000037/

(tested the problems other user on 1.2 reported at the Athom forum - https://forum.athom.com/discussion/3138/spraak-gebrek-homey)

**What was the result?**

![knipsel](https://cloud.githubusercontent.com/assets/8224586/25610478/a66a046e-2f23-11e7-8269-1133065a5a58.PNG)

**What did you expect as result?**
A timer was set

**Any other remarks**

**Comment by Tweake** [comment] 2017-05-02 09:53
Same as #29, will be fixed in rc4

**Comment by lubbertkramer** [comment] 2017-05-03 19:54
Got 1.3RC4 running now and tested it again (copy paste frm the website) but now got the message that Homey is sorry but he didn't understand me

![capture](https://cloud.githubusercontent.com/assets/8224586/25678705/f8ed7144-304a-11e7-83a3-374a3dc7e577.PNG)

**Comment by Tweake** [comment] 2017-05-04 10:48
This is an interesting one. It turns out the issue is specific to the combination of Facebook messenger and Dutch commands. Fortunately it is something we can fix, though this will take some time.

In the mean time, typing the command at <homey-ip>/manager/speech-input/ or saying it through a microphone will still allow you to set a timer successfully.

**Comment by Tweake** [comment] 2017-05-08 11:27
This has been fixed. To verify that it's working you will need to log out with Messenger and log back in again (click the three blue lines next to the text field)

**Comment by lubbertkramer** [comment] 2017-05-08 11:32
Tested it and working now. Thanks!

**Closed** 2017-05-08 11:33 UTC
Labels: Staged for release
