### ISSUE TITLE
Fibaro dimmer 2 keeps spinning after sending command using flow

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#95] opened 2017-09-03 19:00 UTC
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**
i tryd to dimm several fibaro dimmers using a flow
(card 30 sec to dim to example 80%)
(card set dim to 80%)

*Please include detailed steps how we can reproduce the issue*
create a new flow and dim the dimmers to 80 %

**What was the result?**
the fibaro dimmers 2 sometimes dim most of the times the card in the flow kept spinning
...

**What did you expect as result?**
that the dimmer would dim
...

**Any other remarks**
did several reboots
did reset the micro controller
...
log code
5C7AD8F97A

zwave log
[Untitled.txt](https://github.com/athombv/homey-issues-dp/files/1273148/Untitled.txt)

**Comment by RobinBol** [comment] 2017-10-16 14:55
Closing this issue as it is a duplicate of: https://github.com/athombv/com.fibaro/issues/164. Thanks for reporting!

**Closed by RobinBol** 2017-10-16 14:55 UTC
