### ISSUE TITLE
1.5.4-rc1 zigbee delay

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#116] opened 2017-10-21 12:41 UTC
**What is your Homey version (Settings → System)?**

1.5.4-rc1

**What did you try to achieve?**
if i trigger the hue motion sensor (zigbee) i get 3-4 sec delay

*Please include detailed steps how we can reproduce the issue*
the delay has been introduced since 1.5.4-rc1

**What was the result?**
1.5.4-rc1
...

**What did you expect as result?**
no delay like 1.5.3
...

**Any other remarks**

...

**Comment by robiebab** [comment] 2017-10-21 20:54
re-including fixed the problem:

Homey 1.5.4-rc.1
[ZigBee] Moved HA cluster to endpoint 1.

On 1.5.3 HA cluster was linked to endpoint 2; now to endpoint 1...

**Comment by jeroenvollenbrock** [comment] 2017-10-30 21:31
A re-include should not be required, @RobinBol: i guess you need more information such as a log to make sense of this, right?

**Comment by RobinBol** [comment] 2017-11-20 16:37
@robiebab does this happen often? Or was it just when migrating from 1.5.3 to 1.5.4? And please include relevant logs in these sorts of issues!

**Comment by robiebab** [comment] 2017-11-22 11:04
hi robin, from 1.5.3 -> 1.5.4 i did get the delay all the time (don't have logs), now only some times if it happens i post the logs

**Comment by RobinBol** [comment] 2017-11-23 10:52
Ok, well a sporadic small delay of a few seconds is not really a bug in my opinion, it could be caused by many things. If this happens consistently then it might be worth looking into.

So, I will close this issue for now. If this issue becomes worse for you then please let us know.

**Closed by RobinBol** 2017-11-23 10:52 UTC
Labels: bug, waiting for user feedback, ZigBee
