### ISSUE TITLE
No Ok Homey detection

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey-issues-dp#12] opened 2017-03-13 18:54 UTC
**What is your Homey version (Settings → System)?**

1.2.0 RC 6

**What did you try to achieve?**

No response on the Ok Homey detection, speech works fine via app or the speech-input page.

**Comment by mruiter** [comment] 2017-03-14 15:23
Same here

**Comment by WeeJeWel** [comment] 2017-03-22 15:17
Duplicate of #13 (?)

**Closed by WeeJeWel** 2017-03-22 15:17 UTC
