### ISSUE TITLE
Restart pls wait msg disapears before homey restarts.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey-issues-dp#17] opened 2017-03-28 20:27 UTC
**What is your Homey version (Settings → System)?**
Homey Firmware Version: 1.2.0-rc.10

**What did you try to achieve?**
Restart Homey 

*Please include detailed steps how we can reproduce the issue*
use Chrome (but that shouldn't matter ;-) )
Got to settings - Reboot / Opnieuw Opstarten

**What was the result?**
Black overlay with:  "Homey is restarting please wait..."
for 3 or 4 seconds, then the "/manager/settings/#homey:manager:system" page reloaded.....
Homey was still preparing to restart and my Ping reply's disappeared 5 -10 seconds later....

**What did you expect as result?**
as with the other versions until rc9 -> Black overlays with the pls wait msg until Homey is restarted (maybe minutes later....)

**Any other remarks**
Optimizations .... Optimizations .... making everything faster,  Great!!!! 
( and  again  a new problem ;-) maybe make Homey restart faster to comply with the msg  )

**Comment by TheMSB** [comment] 2017-04-10 09:34
@Dijker I found the cause and it will be fixed with the next release.

**Closed by TheMSB** 2017-04-10 09:34 UTC
Labels: bug
