### ISSUE TITLE
Turn off a zone won't work 

### ISSUE THREAD

**Issue by Jovink** [athombv/homey-issues-dp#161] opened 2018-02-26 20:39 UTC
**What is your Homey version (Settings → System)?**

1.5.7

**What did you try to achieve?**
made a flow 
If flow starts then turn off the lights on the begane grond

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
lights won't switch 

**What did you expect as result?**

Lights goes off 

**Any other remarks**

...
It's specifically a main zone. sub zone does work

**Comment by WeeJeWel** [comment] 2018-03-05 18:13
Please include more information, this is very limited and doesn't give us a clue where to begin debugging the issue.

**Comment by Jovink** [comment] 2018-03-05 18:46
![1335a628-b36c-45bd-9858-9d43310ce13a](https://user-images.githubusercontent.com/16411340/36992944-b7e2de98-20ac-11e8-8fbc-301c8bed3ad3.png)
Standaard komt Homey met de volgende indeling 

Thuis 
   Begane grond
        Woonkamer 
         Keuken
         Toilet
   Eerste verdieping 
          Slaapkamer
          Badkamer 
          Studeerkamer
Zolder
Kelder
Tuin
Schuur 

Met de gemaakte flow zou je verwachten dat alle lampen
In de keuken, woonkamer en toilet uit geschakeld worden 
Bij het starten van deze flow.  Maar dat gebeurt dus niet 
Alleen als je ipv begane grond woonkamer selecteerd kan je woonkamer 
Schakelen. Terwijl je (ik) verwacht dat met de gemaakte flow de hele 
Begane grond geschakeld wordt omdat woonkamer, keuken, toilet  onderdeel zijn 
Van begane grond.

**Comment by Dijker** [comment] 2018-03-05 22:16
@Jovink 
duplicate of https://github.com/athombv/homey/issues/1925 ? 
or what is your request other then issue 1925 en specific for the DP release?

If I am correct the homey-issues-dp Issue tracker is specific for (new) Issues that are introduced in the DP releases we get and/or issues in new introduced (alpha) functionality not yet in the experimental and Stable channel....

**Comment by Jovink** [comment] 2018-03-06 06:48
Guess you’re right. 
Jeroen ask me to create a issue when we talk about it. 
Didn’t now there was a issue already

**Comment by Dijker** [comment] 2018-03-06 06:52
So now you can close it yourself @Jovink :-)

**Closed** 2018-03-06 14:50 UTC
