### ISSUE TITLE
1.5.2 (card invisible) move card from else column to then

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#97] opened 2017-09-12 11:03 UTC
**What is your Homey version (Settings → System)?**

1.5.2
osx app

**What did you try to achieve?**
I wan't to move a card (in this case flow card) from an excisting flow to the then flow

*Please include detailed steps how we can reproduce the issue*
-open an excisting flow with cards in the else column
-move a card from else to the then column

**What was the result?**
card is invisible
...
<img width="1280" alt="schermafbeelding 2017-09-12 om 12 59 09" src="https://user-images.githubusercontent.com/18186327/30322749-d22f4a5a-97ba-11e7-9f04-af6641a7da28.png">

**What did you expect as result?**
card can be removed
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment] 2017-10-31 14:45
I cannot reproduce this issue - is it still happening?

**Comment by robiebab** [comment] 2017-10-31 20:08
I reproduced it today 1.5.4 rc2

i uploaded the screenrecording:
https://ufile.io/7yur7

i tested it on two flows 
1 went fine
2 i got this issue the hole time (flow: Lichten - Aan)

**Comment by WeeJeWel** [comment] 2017-11-02 13:33
Thanks for the video. As it's not a blocker but mere a conveniency, we won't fix it due to our focus on the upcoming Homey Smartphone App.

**Closed by WeeJeWel** 2017-11-02 13:33 UTC
Labels: bug, Interface
