### ISSUE TITLE
No response to OK Homey

### ISSUE THREAD

**Issue by gruijter** [athombv/homey-issues-dp#13] opened 2017-03-13 21:49 UTC
**What is your Homey version (Settings → System)?**

1.2.0 rc6

**What did you try to achieve?**

Homey is not responding to ok homey anymore

*Please include detailed steps how we can reproduce the issue*

It happened after a flow got triggeted that uses voice confirmation

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

DF74BD5F44

**Comment by mruiter** [comment] 2017-03-14 15:23
Same here

**Comment by WeeJeWel** [comment] 2017-03-15 16:48
I cannot reproduce, or I don't understand the issue correctly. What I've tried:

'OK Homey, what time is it?' -> Homey responds
'OK Homey, hello world' -> Homey asks 'Please confirm' -> 'Yes' -> 'OK'
'OK Homey, what time is it?' -> Homey responds

![screen shot 2017-03-15 at 17 47 54](https://cloud.githubusercontent.com/assets/319873/23960210/a1951a6a-09a7-11e7-9461-54df568322a8.png)

**Comment by gruijter** [comment] 2017-03-15 16:59
Yes, this is what made my homey unresponsive to 'ok homey'. It said the 'please confirm' part, but the ring did not turn white and after that it did not listen at all anymore. The log I sent was before I did a restart, which fixed the issue.

**Comment by WeeJeWel** [comment] 2017-03-16 12:17
Alright. I think this has been fixed already, so please confirm after testing rc.7

**Comment by WeeJeWel** [comment] 2017-03-22 14:39
Could someone confirm if this is fixed or still an issue?

**Comment by gruijter** [comment] 2017-03-22 15:11
I havent had it since the latest update. Also I removed some apps. Might be a resource problem

**Comment by WeeJeWel** [comment] 2017-03-22 15:17
I'll close it until someone experiences it again

**Closed by WeeJeWel** 2017-03-22 15:17 UTC
