### ISSUE TITLE
[AppV2 v.104] Dead device cannot be deleted in flow

### ISSUE THREAD

**Issue by cbho** [athombv/homey-issues-dp#136] opened 2017-12-13 09:20 UTC
Fw 1.5.6-rc6
App 1.1.104
iOS 11.1.2, iPhone SE

**What did you try to achieve?**
Delete a flow card in a flow referring to a removed device.

*Please include detailed steps how we can reproduce the issue*
A removed device (excluded from the z-wave network on purpose) which has not yet been removed from the flow in the desktop app is imarked as "This card is unavailable" in the mobile app

**What was the result?**
The card cannot be deleted.
Nothing happens when trying to access the card, neither is it possible to delete it.

**What did you expect as result?**
That I could.

**Any other remarks**
![2017-12-12 18 50 37](https://user-images.githubusercontent.com/29979509/33931205-9ac394c2-dfef-11e7-86ef-11a393f69b91.png)

**Comment by jeroenvollenbrock** [comment] 2017-12-13 16:05
Closed as duplicate of https://github.com/athombv/homey/issues/2040

**Closed by jeroenvollenbrock** 2017-12-13 16:05 UTC

**Comment by cbho** [comment] 2017-12-13 16:07
Sorry - didn't find the other when searching.
