### ISSUE TITLE
[1.5.6.RC10] free memory doesn't reflect the memory bar

### ISSUE THREAD

**Issue by robiebab** [athombv/homey-issues-dp#153] opened 2018-02-03 21:57 UTC
**What is your Homey version (Settings → System)?**

[1.5.6.RC10]

**What did you try to achieve?**
when i look into stuff for geeks -> freemem_human i see less memory free then is reflected into the memory bar

**What was the result?**
<img width="892" alt="schermafbeelding 2018-02-03 om 22 48 45" src="https://user-images.githubusercontent.com/18186327/35771946-7fd2de42-0935-11e8-9131-29e27fa794f5.png">

<img width="221" alt="schermafbeelding 2018-02-03 om 22 49 29" src="https://user-images.githubusercontent.com/18186327/35771949-83ce559e-0935-11e8-8341-590c1800c1b1.png">

**What did you expect as result?**
i would expect those 2 to reflect the same in grafics
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment] 2018-02-05 17:29
Closed as duplicate of https://github.com/athombv/homey/issues/1789

**Closed by jeroenvollenbrock** 2018-02-05 17:29 UTC
